# Generated by Django 4.1.5 on 2023-01-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_year', models.IntegerField(blank=True, default=1, null=True)),
                ('intensity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
