# Generated by Django 4.1.5 on 2023-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0003_alter_datadata_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadata',
            name='added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='published',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
