# Generated by Django 4.1.5 on 2023-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0004_alter_datadata_added_alter_datadata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadata',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
