# Generated by Django 4.1.5 on 2023-01-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0006_remove_datadata_insight_alter_datadata_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadata',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
