# Generated by Django 4.1.5 on 2023-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0007_datadata_insight_alter_datadata_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadata',
            name='end_year',
            field=models.TextField(default=0),
        ),
    ]
