# Generated by Django 4.1.5 on 2023-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0008_alter_datadata_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadata',
            name='country',
            field=models.TextField(default='starnge country'),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='intensity',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='likelihood',
            field=models.TextField(default=0),
        ),
    ]
