# Generated by Django 4.1.5 on 2023-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize2', '0009_alter_datadata_country_alter_datadata_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadata',
            name='impact',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='pestle',
            field=models.TextField(default='pestle'),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='region',
            field=models.TextField(default='region'),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='relevance',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='datadata',
            name='start_year',
            field=models.TextField(default=0),
        ),
    ]
